# fly.toml app configuration file generated for fastify-starter on 2024-03-26T21:05:45+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastify-starter'
primary_region = 'sin'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[checks]
[checks.api_health_check]
grace_period = "30s"
interval = "15s"
method = "get"
path = "/health/check"
port = 3000
timeout = "10s"
type = "http"


[[vm]]
size = 'shared-cpu-1x'
