name: CI
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Git version
    steps:
       - name: 🛑 Cancel Previous Runs
         uses: styfle/cancel-workflow-action@0.9.1

       - name: ⬇️ Checkout repo
         uses: actions/checkout@v3

       - name: ⎔ Setup node
         uses: actions/setup-node@v3
         with:
          node-version: 16

       - name: 📥 Download deps
         uses: bahmutov/npm-install@v1

       - name: Install GitVersion
         uses: gittools/actions/gitversion/setup@v0.9.7
         with:
          versionSpec: "5.x"

       - name: Determine Version
         uses: gittools/actions/gitversion/execute@v0.9.7
         with:
           useConfigFile: true

       - name: Display SemVer
         run: |
            echo "SemVer: $GITVERSION_SEMVER"